// <auto-generated />
namespace Gamers.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Modificaciondelatablajuegosprimarykeymaxlengthyunique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modificaciondelatablajuegosprimarykeymaxlengthyunique));
        
        string IMigrationMetadata.Id
        {
            get { return "202006152309458_Modificacion de la tabla juegos,primary key,max length y unique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
