// <auto-generated />
namespace Gamers.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Agrego_campos_Tabla_imagenesJuego : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agrego_campos_Tabla_imagenesJuego));
        
        string IMigrationMetadata.Id
        {
            get { return "202006170037172_Agrego_campos_Tabla_imagenesJuego"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
