// <auto-generated />
namespace Gamers.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Modifico_Juego_maxlengh_descripcion_Relacion_Categoria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modifico_Juego_maxlengh_descripcion_Relacion_Categoria));
        
        string IMigrationMetadata.Id
        {
            get { return "202006162305197_Modifico_Juego_maxlengh_ descripcion_Relacion_Categoria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
