// <auto-generated />
namespace Gamers.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ModificotablaCategoriaAgregonulleablealaedad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModificotablaCategoriaAgregonulleablealaedad));
        
        string IMigrationMetadata.Id
        {
            get { return "202006131924282_Modifico tabla Categoria  Agrego nulleable a la edad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
